### PR TITLE
Add travis config

### PR DESCRIPTION
**Pull request by anuragsoni**

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM, though I note that the utop travis config includes a package name, i.e.

```
  global:
  - PACKAGE=utop
```

**Comment by pmetzger** [comment]
I'm going to merge this for now, but I'd like it if @diml would have a look at it tomorrow.

**Comment by diml** [comment]
LGTM. BTW, nowadays I use [autoci](https://github.com/yomimono/autoci) to generate the travis files. I just accept what it gives without looking at it much. We are planning to allow writing `(using travis)` in `dune-project` files so that the travis file can be kept up-to-date automatically.

**Comment by anuragsoni** [comment]
I did not know about autoci! That looks good. FWIW i used [ocaml ci scripts](https://github.com/ocaml/ocaml-ci-scripts)

`dune` helping keep the ci files up-to-date sounds really good! `dune` keeps getting better!

**Pull request merged**
