### PR TITLE
Replace camomile with uucd/uutf

### PR DESCRIPTION
**Pull request by nojb**
Following discussion in #14 I dusted off my old patch and am submitting it for consideration. NB:

1) this patch removes all the regexp-related code from the library, including the whole `Zed_re` module;
2) in particular the default `match_word` function passed to `Zed_edit.create` is dummy stub that doesn't match anything, and
3) the lowercase/uppercase functions (see `Zed_rope.{lowercase,uppercase}`) do not take into account locale information, which seems to require some information not yet exposed in `uucd`. @dbuenzli : is there a way to access the "condition" data in https://unicode.org/Public/UNIDATA/SpecialCasing.txt using `uucd`? 

/cc @Drup @diml

### CODE REVIEW

**Comment by nojb** [comment]
The important thing is to see how much breakage this causes in `lambda-term` and other downstream packages.

**Comment by dbuenzli** [comment]
> @dbuenzli : is there a way to access the "condition" data in https://unicode.org/Public/UNIDATA/SpecialCasing.txt using `uucd`?

No because these are no longer part of the unicode character database. From the [UAX44]:

```
The special casing conditions associated with case mapping for Greek,
Turkish, and Lithuanian are specified in an additional field in
SpecialCasing.txt. For example, the lowercase mapping for sigma in
Greek varies according to its position in a word. The condition list
does not constitute a formal character property in the UCD, because it
is a statement about the context of occurrence of casing behavior for
a character or characters, rather than a semantic attribute of those
characters. Versions of the UCD from Version 3.2.0 to Version 5.0.0
did list property aliases for Special_Case_Condition (scc), but this
was determined to be an error when the UCD was analyzed for
representation in XML; consequently, the Special_Case_Condition
property aliases were removed as of Version 5.1.0.
```

and from the file you linked:

```
# Note that the preferred mechanism for defining tailored casing operations is
# the Unicode Common Locale Data Repository (CLDR). For more information, see the
# discussion of case mappings and case algorithms in the Unicode Standard.
```
See also this [FAQ](http://unicode.org/faq/casemap_charprop.html#5)

**Comment by nojb** [comment]
> No because these are no longer part of the unicode character database.

Thanks, I had missed that!

**Comment by nojb** [comment]
I restored the `match_word` functionality using code from the `zed-2` branch by @diml.

**Comment by Drup** [comment]
@nojb This is exciting!

I'm not sure what to think of the regular expression aspect. lambda-term seems to only use regular expressions to recognize words for `Zed_edit.create`, so probably something that could be handled in another way.

If we were *before* the release 2.0, I would suggest to make a point-release where the functions are deprecated, and then release 2.0 without the regexps, but that plan seem compromised now.

**Comment by Drup** [comment]
(Would it be sacrilegious to propose to withdraw 2.0 from the opam repository, make a big bunch of breaking changes, including the bundling of everything under a big `Zed` module, and integration of the changes made by @diml in his branch, and then release a 2.1 release that would be the "proper" one ?)

**Comment by pmetzger** [comment]
Integers are inexpensive. I think creating a 3.0 is just fine.

**Comment by kandu** [comment]
It seems zed is advancing like a rocket.

**Comment by diml** [comment]
> Integers are inexpensive. I think creating a 3.0 is just fine.

Agreed

**Comment by kandu** [comment]
Speaking of zed 3.0, we now agreed that the current api of zed 2 and lambda-term 2 is rough and there is room for improvements.
https://github.com/ocaml-community/zed/pull/18#issuecomment-498513364
I think we may wait for a little bit longer until the improvements are done. Otherwise, the zed rocket will release 4.0 just after 3.0. Users of zed and downstream projects will hurry running after the zed rocket.

**Comment by diml** [comment]
> I think we may wait for a little bit longer until the improvements are done. Otherwise, the zed rocket will release 4.0 just after 3.0. Users of zed and downstream projects will hurry running after the zed rocket.

Good idea, that's a wise decision

**Comment by pmetzger** [comment]
@nojb Please resolve the conflicts?

**Comment by pmetzger** [comment]
On the version number question: I agree that it's okay if we hold of releasing for a bit so we can patch up all the APIs at once. That said, lets be bold about fixing this, and lets not worry _too_ much about wasting integers.

**Comment by Drup** [comment]
So where are we on this. Are there some remaining blockers ?

**Comment by pmetzger** [comment]
@Drup At the very least, @nojb needs to resolve the conflicts.

**Comment by nojb** [comment]
This needs updating, but I don't have the time at the moment.

**Pull request closed without merging**
